version: "3"
services:
  entity-generator:
    build:
      context: backend/
      dockerfile: Dockerfile.generate_entity
    volumes:
      - ./backend/src/entities/:/app/src/entities
    depends_on:
      - db
    networks:
      - back-db
    env_file:
      - .env.dev
  db:
    image: docker.io/postgres:latest
    volumes:
      - ./db-data/:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    networks:
      - back-db
    env_file:
      - .env.dev

networks:
  back-db: {}
