version: "3"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    working_dir: /app
    # Bind all important files over
    # Notably, node_modules and .svelte-kit are not bound
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/static:/app/static
      - ./frontend/postcss.config.js:/app/postcss.config.js
      - ./frontend/svelte.config.js:/app/svelte.config.js
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/vite.config.ts:/app/vite.config.ts
    # depends_on:
    #   - backend
    ports:
      - 5173:5173
    # Run command
    command: [ "bun", "--bun", "run", "dev", "--", "--host" ]

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - back-db
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - RUST_LOG=info
    env_file:
      - .env.dev
    ports:
      - 3000:3000
  # migrator:
  #   build:
  #     context: backend/migration
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #   networks:
  #     - back-db
  #   env_file:
  #     - .env.dev
  db:
    image: docker.io/postgres:latest
    volumes:
      - ./db-data/:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    networks:
      - back-db
    env_file:
      - .env.dev
  adminer:
    image: docker.io/adminer:latest
    restart: always
    depends_on:
      - db
    networks:
      - back-db
    ports:
      - 8080:8080

networks:
  back-db: {}
