FROM docker.io/rust:1.72 AS entity-generator
RUN cargo install sea-orm-cli
RUN rustup component add rustfmt
WORKDIR /app
ENTRYPOINT "/usr/local/cargo/bin/sea-orm-cli" "generate" "entity" "-o" "src/entities" "--model-extra-derives" "poem_openapi::Object"